name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'
      - name: Install dependencies
        run: |
          cd server && npm ci
          cd ../client && npm ci
      - name: Run server tests
        run: |
          cd server && npm test
      - name: Run client tests
        run: |
          cd client && npm test
